name: Unzip folders
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -o app.zip
          unzip -o gradle.zip
          unzip -o public.zip
          rm app.zip gradle.zip public.zip
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add.
          git commit -m "extracted" || true
          git push
